### ISSUE TITLE
Error when importing latest shapely version installed with pip

### ISSUE THREAD

**Issue by DoTha** [shapely/shapely#1567]
Trying to import geopandas I get the following shapely-related error:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/5963811/195568265-46675a9b-8a20-49c1-ae69-a62e4746e485.png">

I also got the following warning when shapely was installed via pip:
Collecting shapely>=1.6
  Downloading Shapely-1.8.5.tar.gz (200 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  WARNING: Missing build requirements in pyproject.toml for shapely>=1.6 from https://files.pythonhosted.org/packages/21/d0/82ea9573c9ba8e7a5709ee08681249ad25411382f6440f548981286f3b74/Shapely-1.8.5.tar.gz#sha256=e82b6d60ecfb124120c88fe106a478596bbeab142116d7e7f64a364dac902a92

**Comment by rmvanhees** [comment]
Strange according to the installation files Shapely requires python >=3.7 (but not according to the PyPI website). Thus you can expect problems when you try to run Shapely using python 3.6

Maybe you should try: "pip3 install -U --no-binary=Shapely Shapely", then you force pip to compile Shapely using the locally installed geos library.

**Comment by jorisvandenbossche** [comment]
> Strange according to the installation files Shapely requires python >=3.7

I suppose you checked the main branch, but so for 1.8.x, we have >= 3.6:

https://github.com/shapely/shapely/blob/f02c4c72d29862ade0708ce777d0316fbba44fef/setup.py#L203

However, it seems that we (maybe accidentally) stopped uploading binary wheels for Python 3.6 for shapely 1.8.5 (https://pypi.org/project/Shapely/#files), while before we had wheels for 3.6 as well.

So as a result, it is download the source distribution, and trying to install shapely from source. But in that case, we expect that the user has installed GEOS on its system. And that is probably not the case here, explaining the error we see.

cc @sgillies

**Comment by sgillies** [comment]
@DoTha I'll get wheels for 3.6 up on PyPI this morning.

**Comment by sgillies** [comment]
Done! https://pypi.org/project/Shapely/1.8.5.post1/#files

**Comment by EwoutH** [comment]
@DoTha Note however that Python 3.6 has reached end-of-life and is no longer supported with security or other updates. Many packages have already dropped support for it, especially if they're following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). So it's highly recommended to update your Python installation.

**Comment by DoTha** [comment]
thx a lot! :)

**Comment by bertsky** [comment]
@sgillies something is still wrong with the 1.8.5.post1 wheels though:
```sh
python -c "from shapely.geometry import Polygon; import torch; torch.randn(10).cuda()"
Segmentation fault (core dumped)
```

(This is the minimal example I could come up with. There are lots of real segfaults when doing other CUDA stuff with this version of Shapely.)

It goes away with importing all of Shapely. It also goes away when installing 1.8.5.post1 from source (`pip install --no-binary shapely --force-reinstall shapely` or `pip install --force-reinstall git+https://github.com/shapely/shapely@maint-1.8`).

This is Linux with Python 3.8. (I tried different versions of Pytorch and CUDA toolkit – always the same.)

Should I open a new issue for this?
