### ISSUE TITLE
Applied to a rectangle `minimum_rotated_rectangle` gives a warning

### ISSUE THREAD

**Issue by DOSull** [shapely/shapely#2215]
When I request the minimum rotated rectangle of a rectangle, I get a divide by zero warning.

```
from shapely.geometry import *
Polygon([Point(-100, -100), Point(-100, 100), Point(100, 100), Point(100, -100)]).minimum_rotated_rectangle
```
gives

```
/opt/miniconda3/envs/weaving/lib/python3.13/site-packages/shapely/constructive.py:996: RuntimeWarning: divide by zero encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)
```

If I send it a triangle, no such warning is issued

```
Polygon([Point(-100, -100), Point(0, 100), Point(100, -100)]).minimum_rotated_rectangle
```
just shows me the rectangle without complaint (I'm working in a notebook).

It's not a show-stopper - the rectangle is returned either way, but short of me checking that the object I am sending is not a rectangle I can't easily avoid this distracting warning. 

Maybe it's upstream in GEOS. Either way, thought I should report it.

**Comment by theroggy** [comment]
This is indeed something that should be fixed in GEOS. Could you open an issue there and link back to this issue for followup here?

**Comment by DOSull** [comment]
According to `conda list` my environment has 3.13.0 installed. Here (in part) are the versions in the environment I'm using.
```
geos                  3.13.0          hf9b8971_0           conda-forge
python                3.13.1          h4f43103_105_cp313   conda-forge
shapely                2.0.7          py313hb400f68_0      conda-forge
```
I am on MacOS... perhaps there's some difference there. I've confirmed the behaviour in the python interpreter:
```
Python 3.13.1 | packaged by conda-forge | (main, Jan 13 2025, 09:45:31) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import *
>>> Polygon([Point(-100,-100),Point(-100,100),Point(100,100),Point(100,-100)]).\
minimum_rotated_rectangle
/opt/miniconda3/envs/shapely/lib/python3.13/site-packages/shapely/constructive.py:996: RuntimeWarning: divide by zero encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)
<POLYGON ((-100 -100, -100 100, 100 100, 100 -100, -100 -100))>
```
As I said, it's just a warning... it does return the MRR Polygon. Rather odd.

**Comment by theroggy** [comment]
I'm on windows... so that might be the difference. Probably best that you open an issue in the GEOS issue tracker as well (and link back to this issue to follow up)... as it will have to be solved there...

**Comment by martinfleis** [comment]
I think this is an Apple Silicon issue. We had more like before. I'll test that later. I don't remember if we silenced it here or in GEOS.

**Comment by DOSull** [comment]
Good to know I'm not hallucinating it. Reported on GEOS also so it doesn't disappear https://github.com/libgeos/geos/issues/1235

**Comment by jorisvandenbossche** [comment]
There have been a bunch of those warnings that were fixed upstream in GEOS, but I don't think that those were Apple specific (I fixed some of them and could certainly reproduce them on linux). See eg https://github.com/shapely/shapely/issues/1345 and https://github.com/shapely/shapely/issues/1709#issuecomment-1372179187. 

Those warnings can be annoying, but you can typically also ignore them (unless they would point to a bug in GEOS, but if the result is not correct that is probably not the case). In general the problem is that some code in GEOS causes floating point error flags to be set, and then the numpy ufunc machinery picks this up and generates those warnings.

**Comment by johnthagen** [comment]
These warnings hit us when upgrading from shapely 2.0.7 to 2.1.0. We run our unit tests with `-Werror` this results in a failure. These warnings are appearing on macOS ARM64 platform.

```toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
]
```

A minimal reproducer:

```py
from shapely.geometry.polygon import Polygon

coords = ((0.0, 10.0), (0.0, 11.0), (3.0, 11.0), (3.0, 10.0))
polygon = Polygon(coords)
rect = minimum_rotated_rectangle(polygon)
```

Results in this warning:

```
geometry = <POLYGON ((0 10, 0 11, 3 11, 3 10, 0 10))>, kwargs = {}

    @multithreading_enabled
    def _oriented_envelope_geos(geometry, **kwargs):
>       return lib.oriented_envelope(geometry, **kwargs)
E       RuntimeWarning: divide by zero encountered in oriented_envelope
```

Filtering this warning:

```toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:divide by zero encountered in oriented_envelope:RuntimeWarning:shapely",
]
```

Reveals another warning:

```
geometry = <POLYGON ((0 10, 0 11, 3 11, 3 10, 0 10))>, kwargs = {}

    @multithreading_enabled
    def _oriented_envelope_geos(geometry, **kwargs):
>       return lib.oriented_envelope(geometry, **kwargs)
E       RuntimeWarning: invalid value encountered in oriented_envelope
```

To fully suppress this warning in a targeted way, we had to:

```toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:divide by zero encountered in oriented_envelope:RuntimeWarning:shapely",
    "ignore:invalid value encountered in oriented_envelope:RuntimeWarning:shapely",
]
```

**Comment by adamjstewart** [comment]
Just wanted to say we're also experiencing this on Apple Silicon: https://github.com/torchgeo/torchgeo/actions/runs/19045430930/job/54392358476

**Comment by johnthagen** [comment]
We're still seeing these on macOS ARM in shapely 2.1.2 and Python 3.13

```
.venv/lib/python3.13/site-packages/shapely/constructive.py:1353: RuntimeWarning: divide by zero encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)
.venv/lib/python3.13/site-packages/shapely/constructive.py:1353: RuntimeWarning: invalid value encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)
```
